### ISSUE TITLE
How to guide?

### ISSUE THREAD

**Issue by nabeeleinstein** [xusoren/genshin_account_swap#1]
Not an issue, but can you please tell me how it takes the two accounts and switches between them?

**Comment by xusoren** [comment]
Genshin Impact settings and account data saved in registry HKCU\SOFTWARE\miHoYo\Genshin Impact. When you first time run script, it create two folders in registry HKCU\SOFTWARE\miHoYo\Genshin Impact_temp and HKCU\SOFTWARE\miHoYo\Genshin Impact_1 and move first account data in HKCU\SOFTWARE\miHoYo\Genshin Impact_1. Run game and log in to second account. Now you have two data sets and script swaps it(HKCU\SOFTWARE\miHoYo\Genshin Impact -> HKCU\SOFTWARE\miHoYo\Genshin Impact_temp, HKCU\SOFTWARE\miHoYo\Genshin Impact_1 -> HKCU\SOFTWARE\miHoYo\Genshin Impact, HKCU\SOFTWARE\miHoYo\Genshin Impact_temp -> HKCU\SOFTWARE\miHoYo\Genshin Impact_1). Run script when game closed.

**Comment by nabeeleinstein** [comment]
Thank you.
